export const ACHIEVEMENT_DEFINITIONS = [
  // --- Workout Milestones ---
  {
    code: 'WORKOUT_1',
    type: 'WORKOUT_MILESTONE',
    name: 'First Step',
    description: 'Completed your very first logged workout.',
    badgeIcon: 'footsteps',
    threshold: 1,
    check: (stats) => stats.totalWorkouts >= 1,
  },
  {
    code: 'WORKOUT_5',
    type: 'WORKOUT_MILESTONE',
    name: 'Consistency Kickoff',
    description: 'Completed 5 logged workouts.',
    badgeIcon: 'calendar-check',
    threshold: 5,
    check: (stats) => stats.totalWorkouts >= 5,
  },
  {
    code: 'WORKOUT_10',
    type: 'WORKOUT_MILESTONE',
    name: 'Iron Habit',
    description: 'Completed 10 logged workouts.',
    badgeIcon: 'dumbbell',
    threshold: 10,
    check: (stats) => stats.totalWorkouts >= 10,
  },
  {
    code: 'WORKOUT_25',
    type: 'WORKOUT_MILESTONE',
    name: 'Quarter Century',
    description: 'Completed 25 logged workouts.',
    badgeIcon: 'trophy',
    threshold: 25,
    check: (stats) => stats.totalWorkouts >= 25,
  },
  {
    code: 'WORKOUT_100',
    type: 'WORKOUT_MILESTONE',
    name: 'Century Club',
    description: 'Completed 100 logged workouts. True dedication!',
    badgeIcon: 'crown',
    threshold: 100,
    check: (stats) => stats.totalWorkouts >= 100,
  },

  // --- Volume Milestones (Single Workout) ---
  {
    code: 'VOLUME_500',
    type: 'VOLUME_MILESTONE',
    name: 'Warmup Warrior',
    description: 'Lifted over 500 kg total volume in a single workout.',
    badgeIcon: 'weight',
    threshold: 500,
    check: (stats) => stats.lastWorkoutVolume >= 500 || stats.maxWorkoutVolume >= 500,
  },
  {
    code: 'VOLUME_1000',
    type: 'VOLUME_MILESTONE',
    name: 'Heavy Lifter',
    description: 'Lifted over 1,000 kg total volume in a single workout.',
    badgeIcon: 'fire',
    threshold: 1000,
    check: (stats) => stats.lastWorkoutVolume >= 1000 || stats.maxWorkoutVolume >= 1000,
  },
  {
    code: 'VOLUME_5000',
    type: 'VOLUME_MILESTONE',
    name: 'Ton Crusher',
    description: 'Lifted over 5,000 kg total volume in a single workout.',
    badgeIcon: 'anvil',
    threshold: 5000,
    check: (stats) => stats.lastWorkoutVolume >= 5000 || stats.maxWorkoutVolume >= 5000,
  },
  {
    code: 'VOLUME_10000',
    type: 'VOLUME_MILESTONE',
    name: 'Beast Mode',
    description: 'Lifted an insane 10,000+ kg total volume in a single workout.',
    badgeIcon: 'meteor',
    threshold: 10000,
    check: (stats) => stats.lastWorkoutVolume >= 10000 || stats.maxWorkoutVolume >= 10000,
  },

  // --- Streak Milestones ---
  {
    code: 'STREAK_3',
    type: 'STREAK_MILESTONE',
    name: 'Weekend Warrior',
    description: 'Maintained a 3-day active streak.',
    badgeIcon: 'lightning',
    threshold: 3,
    check: (stats) => (stats.userStreak || 0) >= 3,
  },
  {
    code: 'STREAK_7',
    type: 'STREAK_MILESTONE',
    name: 'Unbreakable',
    description: 'Maintained a 7-day active streak.',
    badgeIcon: 'flame',
    threshold: 7,
    check: (stats) => (stats.userStreak || 0) >= 7,
  },
  {
    code: 'STREAK_14',
    type: 'STREAK_MILESTONE',
    name: 'Iron Discipline',
    description: 'Maintained a 14-day active streak.',
    badgeIcon: 'shield',
    threshold: 14,
    check: (stats) => (stats.userStreak || 0) >= 14,
  },
  {
    code: 'STREAK_30',
    type: 'STREAK_MILESTONE',
    name: 'Monthly Mastery',
    description: 'Maintained a 30-day active streak. Incredible consistency!',
    badgeIcon: 'medal',
    threshold: 30,
    check: (stats) => (stats.userStreak || 0) >= 30,
  },

  // --- Level Up Milestones ---
  {
    code: 'LEVEL_2',
    type: 'LEVEL_UP',
    name: 'Level 2 Novice',
    description: 'Reached User Level 2.',
    badgeIcon: 'star',
    threshold: 2,
    check: (stats) => (stats.userLevel || 1) >= 2,
  },
  {
    code: 'LEVEL_5',
    type: 'LEVEL_UP',
    name: 'Level 5 Warrior',
    description: 'Reached User Level 5.',
    badgeIcon: 'sword',
    threshold: 5,
    check: (stats) => (stats.userLevel || 1) >= 5,
  },
  {
    code: 'LEVEL_10',
    type: 'LEVEL_UP',
    name: 'Level 10 Titan',
    description: 'Reached User Level 10.',
    badgeIcon: 'gem',
    threshold: 10,
    check: (stats) => (stats.userLevel || 1) >= 10,
  },

  // --- Challenge Wins ---
  {
    code: 'CHALLENGE_1',
    type: 'CHALLENGE_WIN',
    name: 'First Blood',
    description: 'Won your first head-to-head challenge.',
    badgeIcon: 'swords',
    threshold: 1,
    check: (stats) => (stats.challengeWins || 0) >= 1,
  },
];
